package com.socal.connection.sri.surabhi.media.utils.Enums;

/**
 * Created by logix028 on 24/11/17.
 */

public enum ScreenEnums {
    SCREEN_NONE,
    SCREEN_HOME,
    SCREEN_EXIT,
    SCREEN_LICENCE,
    SCREEN_SETUP,
    SCREEN_EMAIL,
    SCREEN_PICK_FILE,
    SCREEN_EDIT_PROFILE,
    SCREEN_SUBSCRIPTION,
    SCREEN_UPCOMING_EVENT,
    SCREEN_EXPLORE_SRI_SURBHI,
    SCREEN_REFEAR_A_FRIEND,
    SCREEN_SUBSCRIPTION_MEMBER_SHIPS,
    SCREEN_GO_Seva, SCREEN_PANCHGAVYA,
    SCREEN_SURABHI_MEDIA,
    SCREEN_VRT,
    SCREEN_SURABHI_CONNECT,
    SCREEN_GET_INVOLVED,
    SCREEN_SUPPORT,
    SCREEN_PAYMENT, SCREEN_NEWS_FEED, SCREEN_ALL_ABOUT_COWS_SCREEN
}
